In [5]:
# 1) Düz array oluşturma
arr1 = np.array([1, 2, 3, 4, 5])
print("np.array:", arr1)

# 2) Aralık ile array oluşturma (0’dan 9’a kadar)
arr2 = np.arange(0, 10)
print("np.arange:", arr2)

# 3) Random array (0–1 arası 5 sayı)
arr3 = np.random.rand(5)
print("np.random.rand:", arr3)

# 4) Random integer array (0–50 arası 5 sayı)
arr4 = np.random.randint(0, 50, 5)
print("np.random.randint:", arr4)


np.array: [1 2 3 4 5]
np.arange: [0 1 2 3 4 5 6 7 8 9]
np.random.rand: [0.06351252 0.02301597 0.93122988 0.83471753 0.59024239]
np.random.randint: [46 29 43 32 39]


In [6]:
import numpy as np

# Bir array oluşturalım
a = np.arange(10)   # 0'dan 9'a kadar
print("Array:", a)

# Shape (boyut bilgisi)
print("Shape:", a.shape)

# Dtype (veri tipi)
print("Dtype:", a.dtype)

# Slicing (dilimleme)
print("İlk 5 eleman:", a[:5])
print("Son 3 eleman:", a[-3:])
print("2'den 7'ye kadar:", a[2:8])


Array: [0 1 2 3 4 5 6 7 8 9]
Shape: (10,)
Dtype: int64
İlk 5 eleman: [0 1 2 3 4]
Son 3 eleman: [7 8 9]
2'den 7'ye kadar: [2 3 4 5 6 7]


In [7]:
import numpy as np

# 3x3 matris oluşturalım
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Orijinal matris:\n", m)

# Transpoz (satır ↔ sütun değişir)
print("Transpoz:\n", m.T)


Orijinal matris:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpoz:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [8]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("a:", a)
print("b:", b)

# 1) Tüm elemanları 2 ile çarp
print("a * 2:", a * 2)

# 2) İki array'i topla
print("a + b:", a + b)

# 3) Eleman bazlı çarpım
print("a * b:", a * b)

# 4) Eleman bazlı karesini al
print("a ** 2:", a ** 2)


a: [1 2 3 4 5]
b: [10 20 30 40 50]
a * 2: [ 2  4  6  8 10]
a + b: [11 22 33 44 55]
a * b: [ 10  40  90 160 250]
a ** 2: [ 1  4  9 16 25]


In [3]:
import numpy as np
