## Day 2 — NumPy Exercises
### Project: NumPy-only Linear Regression (GD vs Closed-form)


In [7]:
import numpy as np
np.random.seed(42)


In [8]:
n = 600


In [9]:
size_m2     = np.random.uniform(50, 200, n)
rooms       = np.random.randint(1, 7, n)
age         = np.random.uniform(0, 30, n)
distance_km = np.random.uniform(0, 20, n)

print(size_m2[:5])
print(rooms[:5])


[106.18101783 192.60714596 159.79909127 139.79877263  73.40279607]
[5 2 4 2 5]


In [10]:
X = np.column_stack([size_m2, rooms, age, distance_km])
print(X.shape)
print(X[:5])


(600, 4)
[[106.18101783   5.          17.70692001   2.08219299]
 [192.60714596   2.          10.82921691  14.48677634]
 [159.79909127   4.           2.7474622   11.56773834]
 [139.79877263   2.          27.51940726   5.48321333]
 [ 73.40279607   5.           4.10455893   1.58838738]]


In [11]:
true_w = np.array([3000.0, 20000.0, -1500.0, -2500.0])
true_b = 50_000.0
print(true_w)


[ 3000. 20000. -1500. -2500.]


In [12]:
noise = np.random.normal(0, 15000, n)
y = X @ true_w + true_b + noise

print(y.shape)
print(y[:5])


(600,)
[422282.50521652 617612.71341129 550783.55635313 420254.30555188
 362193.00775621]


In [13]:
# 80% train, 20% test ayır
idx = np.arange(n)
np.random.shuffle(idx)

train_size = int(0.8 * n)
train_idx, test_idx = idx[:train_size], idx[train_size:]

X_train, X_test = X[train_idx], X[test_idx]
y_train, y_test = y[train_idx], y[test_idx]

print("Train shape:", X_train.shape, y_train.shape)
print("Test shape:", X_test.shape, y_test.shape)

# Standardizasyon (ortalama 0, std 1)
mean, std = X_train.mean(axis=0), X_train.std(axis=0)
X_train_std = (X_train - mean) / std
X_test_std = (X_test - mean) / std

# Bias için 1’ler sütunu ekle
X_train_std = np.column_stack([np.ones(X_train_std.shape[0]), X_train_std])
X_test_std  = np.column_stack([np.ones(X_test_std.shape[0]),  X_test_std])

print("Final train shape:", X_train_std.shape)
print("Final test shape:", X_test_std.shape)


Train shape: (480, 4) (480,)
Test shape: (120, 4) (120,)
Final train shape: (480, 5)
Final test shape: (120, 5)
